config/routes.rb
CodeReplacements::Application.routes.draw do
  match 'teams/:id/code' => 'teams#code', :as => :code

  match 'about' => 'about#index'
  match 'teams/custom', :as => :custom_team

  resources :leagues
  resources :teams
  resources :players

  root :to => "leagues#index"

  

end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :name
  has_many :teams, :order => :name, :dependent => :destroy
  belongs_to :sport
  validates_presence_of :name, :short_name, :sport

  def has_females?
    female_teams.size > 0 ? true : false
  end

  def female_teams
    gendered_teams("female")
  end

  def male_teams
    gendered_teams("male")
  end

  def scrape
    if short_name == "NFL" ||
       short_name == "NBA" ||
       short_name == "NCAA FB" ||
       short_name == "NCAA BB" ||
       short_name == "MLB"
      teams.destroy_all
      scrape_espn(male_uri, 'male') if !male_uri.nil?
      scrape_espn(female_uri, 'female') if !female_uri.nil?
    elsif short_name == "MLS"
      teams.destroy_all
      scrape_mls  
    else
      puts "***** #{short_name} not a recognized league."
    end
  end

  def scrape_espn(uri, gender = "male")
    scraper = Scraper.define do
      array :divisions
      process ".mod-container.mod-open-list.mod-teams-list-medium.mod-no-footer", :divisions => Scraper.define {
        array :teams
        process "li", :teams => Scraper.define {
          array :links_href
          process 'a', :links_href => "@href"
          array :links_text
          process 'a', :links_text => :text
          result :links_text, :links_href
        }
        result :teams
      }
      result :divisions
    end
    divisions = scraper.scrape(URI.parse(uri))
    divisions.each do |division|
      division.each do |t|
        team_name_link_id = nil
        team_uri_link_id = nil
        # Pick link IDs based on league type
        if short_name.upcase.include?('NCAA')
          team_name_link_id = 0
          team_uri_link_id = 3
        elsif short_name.upcase == 'NBA' && gender == 'female'
          team_name_link_id = 1
          team_uri_link_id = 4
        else
          team_name_link_id = 0
          team_uri_link_id = 5
        end
        espn_home = "http://espn.go.com"
        team_uri = "#{espn_home}#{t.links_href[team_uri_link_id]}"
        team_name = t.links_text[team_name_link_id].gsub("&amp;","&")
        team = Team.new 
        team.league_id = id
        team.is_custom = false
        team.gender = gender
        team.name = team_name
        team.uri = team_uri
        team.save
      end
    end
  end

  def scrape_mls
    teams = [
      { :name => "Chicago Fire",           :id => "16" },
      { :name => "Chivas USA",             :id => "1"  },
      { :name => "Colorado Rapids",        :id => "2"  },
      { :name => "Columbus Crew",          :id => "15" },
      { :name => "D.C. United",            :id => "14" },
      { :name => "FC Dallas",              :id => "3"  },
      { :name => "Houston Dynamo",         :id => "4"  },
      { :name => "Los Angeles Galaxy",     :id => "8"  },
      { :name => "New England Revolution", :id => "12" },
      { :name => "New York Red Bulls",     :id => "11" },
      { :name => "Philadelphia Union",     :id => "10" },
      { :name => "Portland Timbers",       :id => "52" },
      { :name => "Real Salt Lake",         :id => "7"  },
      { :name => "San Jose Earthquakes",   :id => "6"  },
      { :name => "Seattle Sounders FC",    :id => "5"  },
      { :name => "Sporting Kansas City",   :id => "13" },
      { :name => "Toronto FC",             :id => "9"  },
      { :name => "Vancouver Whitecaps FC", :id => "21" }
    ]
    teams.each do |t|
      team = Team.new 
      team.league_id = id
      team.is_custom = false
      team.gender = "male"
      team.name = t[:name]
      team.uri = t[:url]
      team.uri = "http://www.mlssoccer.com/players?field_player_club_nid=#{t[:id]}"
      team.save
    end
  end

  private

  def gendered_teams(gender)
    Team.where("league_id = ? AND gender LIKE ?", id, gender)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :redirect_to_root, :except => [:index,:show]

  def index
    @league = League.where("is_custom = ?",false).first
    redirect_to @league if !@league.nil?
  end

  def show
    @gender = params[:gender].nil? ? "male" : params[:gender]
    @search = params[:search]
    @league = League.find(params[:id])
    @teams = Team.search(@search).where("league_id = ? AND gender LIKE ?", @league.id, @gender).order(:name).paginate(:per_page => 10, :page => params[:page])
    # Cache results for 5 minutes
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(params[:league])
    if @league.save
      flash[:notice] = "Successfully created league."
      redirect_to @league
    else
      render :action => 'new'
    end
  end

  def edit
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])
    if @league.update_attributes(params[:league])
      flash[:notice] = "Successfully updated league."
      redirect_to league_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy
    flash[:notice] = "Successfully destroyed league."
    redirect_to leagues_url
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.haml
= form_for @league do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.submit

app/views/leagues/_gender_links.html.haml
= link_to 'Men Teams', 
  league_path(:id => @league, :gender => "male"), 
  :class => "button #{'button_selected' if @gender == 'male'}",
  :title => "View Men's #{@league.short_name} League"
= link_to 'Women Teams', 
  league_path(:id => @league, :gender => "female"), 
  :class => "button #{'button_selected' if @gender == 'female'}",
  :title => "View Womens's #{@league.short_name} League"

app/views/leagues/_search_form.html.haml
= text_field_tag :search, @search
%input{:type => :hidden, :name => "gender", :value => @gender}
= submit_tag "Search Teams", :id => "team_search_submit_button", :class => "button", :name => nil, :title => "Search Teams"

app/views/leagues/_teams.html.haml
%p.pagination_info= page_entries_info @teams

%table
  %tr
    %th League
    %th Name
    %th Players
    %th Roster
  - @teams.each do |team|
    %tr
      - title = "View Team Roster For #{team.name}"
      %td= link_to team.league.short_name, team.league, :title => title
      %td= link_to team.name, team, :title => title
      %td= link_to team.players.size, team, :title => title
      %td
        = render :partial => 'teams/download_link', :locals => {:team => team}

= will_paginate @teams, :inner_window => 1, :outer_window => 1

app/views/leagues/edit.html.haml
- title "Edit League"

= render 'form'

%p
  = link_to "Show", @league
  |
  = link_to "View All", leagues_path

app/views/leagues/index.html.haml
- title "Leagues"
%h1= "We are currently updating rosters..."
%p= "Feel free to generate a custom roster while you wait."

app/views/leagues/new.html.haml
- title "New League"

= render 'form'

%p= link_to "Back to List", leagues_path

app/views/leagues/show.html.haml
- @title = "#{@league.short_name}: #{@league.name}"
%h1= @league.name

= form_tag @league, :method => 'get', :id => 'team_search_form' do
  = render :partial => 'search_form'

- if @league.has_females?
  #gender_button_container
    = render :partial => 'gender_links'

#teams
  = render :partial => 'teams'

app/views/leagues/show.js.erb
$('#teams').html("<%= escape_javascript(render('teams'))%>");