config/routes.rb
CodeReplacements::Application.routes.draw do
  match 'teams/:id/code' => 'teams#code', :as => :code

  match 'about' => 'about#index'
  match 'teams/custom', :as => :custom_team

  resources :leagues
  resources :teams
  resources :players

  root :to => "leagues#index"

  

end

app/models/player.rb
class Player < ActiveRecord::Base
    attr_accessible :first_name, :last_name, :number, :position
    validates_presence_of :first_name, :last_name, :number, :position, :team
    belongs_to :team

    def name
      "#{first_name}#{" " if !last_name.nil? && last_name != ""}#{last_name}"
    end

    def position_expanded
      ret = ""
      sport = team.league.sport.name.downcase
      positions = position.split("/")
      positions = position.split("-") if positions.size == 1
      i = 1
      positions.each do |p|
        case sport
        when "baseball"
          case p
          when "OF"
            ret << "outfielder"
          when "1B"
            ret << "first baseman"
          when "2B"
            ret << "second baseman"
          when "3B"
            ret << "third baseman"
          when "SP"
            ret << "setup pitcher"
          when "SS"
            ret << "shortstop"
          when "C"
            ret << "catcher"
          when "CF"
            ret << "center fielder"
          when "LF"
            ret << "left fielder"
          when "RP"
            ret << "relief pitcher"
          when "RF"
            ret << "right fielder"
          else
            ret << p 
          end
        when "basketball"
          case p
          when "SG"
            ret << "shooting guard"
          when "PG"
            ret << "point guard"
          when "PF"
            ret << "point forward"
          when "C"
            ret << "center"
          when "F"
            ret << "forward"
          when "SF"
            ret << "small forward"
          when "G"
            ret << "guard"
          else
            ret << p
          end
        when "soccer"
          case p
          when "M"
            ret << "midfielder"
          when "D"
            ret << "defender"
          when "GK"
            ret << "goalkeeper"
          when "G"
            ret << "goalkeeper"
          when "F"
            ret << "forward"
          else
            ret << p
          end
        when "football"
          case p
          when "QB"
            ret << "quarterback"
          when "RB"
            ret << "running back"
          when "FB"
            ret << "fullback"
          when "DB"
            ret << "defensive back"
          when "WR"
            ret << "wide receiver"
          when "TE"
            ret << "tight end"
          when "C"
            ret << "center"
          when "G"
            ret << "guard"
          when "OT"
            ret << "offensive tackle"
          when "DE"
            ret << "defensive end"
          when "DT"
            ret << "defensive tackle"
          when "LB"
            ret << "linebacker"
          when "CB"
            ret << "cornerback"
          when "S"
            ret << "safety"
          when "PK"
            ret << "placekicker"
          when "P"
            ret << "punter"
          when "K"
            ret << "kicker"
          when "DL"
            ret << "defensive line"
          when "OL"
            ret << "offensive line"
          when "NT"
            ret << "nose tackle"
          when "LS"
            ret << "long snapper"
          else
            ret << p
          end
        else
          ret << p
        end
        if positions.size > 1 && i < positions.size
          ret << "/"
        end
        i = i + 1
      end
      return ret
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :redirect_to_root

  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(params[:player])
    if @player.save
      flash[:notice] = "Successfully created player."
      redirect_to @player
    else
      render :action => 'new'
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(params[:player])
      flash[:notice] = "Successfully updated player."
      redirect_to player_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    flash[:notice] = "Successfully destroyed player."
    redirect_to players_url
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= form_for @player do |f|
  = f.error_messages
  %p
    = f.label :first_name
    %br
    = f.text_field :first_name
  %p
    = f.label :last_name
    %br
    = f.text_field :last_name
  %p
    = f.label :number
    %br
    = f.text_field :number
  %p
    = f.label :position
    %br
    = f.text_field :position
  %p
    = f.submit

app/views/players/edit.html.haml
- title "Edit Player"

= render 'form'

%p
  = link_to "Show", @player
  |
  = link_to "View All", players_path

app/views/players/index.html.haml
- title "Players"

%table
  %tr
    %th Number
    %th First name
    %th Last name
    %th Position
    %th Team
  - for player in @players
    %tr
      %td= link_to player.number, player
      %td= player.first_name
      %td= player.last_name
      %td= player.position
      %td= link_to player.team.name, player.team
      %td= link_to 'Edit', edit_player_path(player)
      %td= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Player", new_player_path(player)

app/views/players/new.html.haml
- title "New Player"

= render 'form'

%p= link_to "Back to List", players_path

app/views/players/show.html.haml
- title @player.name

%p
  %strong First Name:
  = @player.first_name
%p
  %strong Last Name:
  = @player.last_name
%p
  %strong Number:
  = @player.number
%p
  %strong Position:
  = @player.position
%p
  %strong Team:
  = link_to @player.team.name, @player.team

%p
  = link_to "Edit", edit_player_path(@player)
  |
  = link_to "Destroy", @player, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", players_path